version: '3'

services:
  nginx:
    container_name: drippsy_nginx
    build:
      context: api
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./api:/var/www/api
    ports:
      - "8000:80"
    depends_on:
      - db
      - php
    networks:
      - api

  php:
    container_name: drippsy_php
    build:
      context: api
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      - XDEBUG_CONFIG=remote_host=192.168.65.0
      - PHP_IDE_CONFIG=serverName=docker-server
    volumes:
      - ./api:/var/www/api
      - ./api/docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./api/docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      -   api

  db:
    container_name: drippsy_db
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      -   api

  nextjs:
    container_name: drippsy_front
    build:
        context: client
        dockerfile: docker/node/Dockerfile
    networks:
        - client
    volumes:
      - ./client:/var/www/client
    ports:
      - "3000:3000"

networks:
  api:
  client: