version: '3'

services:
  nginx:
    build:
      context: api
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./api:/var/www/api
    ports:
      - "8000:80"
    depends_on:
      - db
      - php
    networks:
      - api

  php:
    build:
      context: api
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./api:/var/www/api
    depends_on:
      - db
    networks:
      -   api

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      -   api

networks:
  api: